### ISSUE TITLE
Unable to use the API

### ISSUE THREAD

**Issue by Lautenschlager-id** [DXsmiley/rtex#1]
While trying to use the API in a language that is not Python I receive the following body response:
```
<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>
```

`code` and `format` were JSON encoded (I tried using the API example)

**Comment by dxsmiley** [comment]
Could you please give some more details? A minimal complete example would help significantly.

**Comment by Lautenschlager-id** [comment]
I translated the following example (in rTeX docs) in two other languages, none of them worked and they do exactly the same as in your example.

```PY
import requests
import shutil

HOST = 'http://63.142.251.124:80'

LATEX = r'''
\documentclass{article}
\begin{document}
\pagenumbering{gobble}
\section{Hello, World!}
This is \LaTeX!
\end{document}
'''

def download_file(url, dest_filename):
	response = requests.get(url, stream = True)
	response.raise_for_status()
	with open(dest_filename, 'wb') as out_file:
		shutil.copyfileobj(response.raw, out_file)

def render_latex(output_format, latex, dest_filename):
	payload = {'code': latex, 'format': output_format}
	response = requests.post(HOST + '/api/v2', data = payload)
	response.raise_for_status()
	jdata = response.json()
	if jdata['status'] != 'success':
		raise Exception('Failed to render LaTeX')
	url = HOST + '/api/v2/' + jdata['filename']
	download_file(url, dest_filename)

render_latex('pdf', LATEX, './out.pdf')
```

The body is returned as 
`<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>`

**Comment by dxsmiley** [comment]
Could you please tell me what those "two other languages" are, and give me the code that you wrote, so that I can reproduce the errors that you're experiencing?

**Comment by Lautenschlager-id** [comment]
_I'm noob_

Sorry, I erased both of them because I found another latex API :cry:
I know someone that is going to use this one in C#. I'll ask him to open another issue if he gets the same problem. Sorry :P
