### ISSUE TITLE
Unable to connect to server (308)

### ISSUE THREAD

**Issue by sriRacha21** [DXsmiley/rtex#3]
I wrote a Discord bot that queries your API. I was initially using [`request-promise`](https://www.npmjs.com/package/request-promise) to access the API, but a few days ago my bot randomly stopped being able to query the API and the server returned status code 308.

Since [`request`](https://www.npmjs.com/package/request) is deprecated I switched to [`bent`](https://www.npmjs.com/package/bent) thinking that might solve the issue.

No dice; I got status code 308 again. In an attempt to figure out what's going on I attempted to make the query through Postman, copying the body from the query I POSTed with my bot and it worked perfectly fine (it might be important to state here that the machine I used Postman with is not the same as the machine that runs my bot).

I'm just wondering if you know what the issue might be?

[Here's the code block in question that attempts to interpret a response from the server.](https://github.com/sriRacha21/Rutgers-kun3/blob/master/helpers/latexInterpreter.js#L45)

Thanks in advance.

**Comment by dxsmiley** [comment]
I recently updated the site to use HTTPS, so you need to update your URI to `https://rtex.probablyaweb.site/api/v2`.

**Comment by sriRacha21** [comment]
Thanks!
